### ISSUE TITLE
Please make bar

### ISSUE THREAD

**Issue by alexdriaguine** [NorthernTwig/Magoon#1]
You know what i mean :hocho: :gun:

**Comment by ShoulderKarlsson** [comment]
Yes. I understand what you are the talking about Mr. alexdriaguine. When aj wanto to you know change the treeview position. I cannot know where to put de mus. Så, please - maek a bar

**Comment by NorthernTwig** [comment]
This is currently not possible with the workbench settings. One could change the colors of the whole treeview, but that would ruin the flatness of the theme. So no can do :rocket: :smile:
