### ISSUE TITLE
Grey fields and Black text. Needs updating.

### ISSUE THREAD

**Issue by kchart90** [NorthernTwig/Magoon#3]
Chrome added some new fields to the inspector and it seems like it broke a bit of this theme. Css text is now black on black, and some new fields are appearing as gray.

**Comment by NorthernTwig** [comment]
What version of Chrome are you using? Also, could you take a screenshot of the inspector :rocket: :+1: ?

**Comment by NorthernTwig** [comment]
Should now be fixed with v.2.0.0.
